@startuml
skinparam classAttributeIconSize 0

abstract class Person {
 #salary: int
 #Person(int: salary)
 +{abstract} getSalary(): int
 +setSalary(int value)
 +setSalary(double value)
 +setSalary(String value)
}

class SelfEmployed {
 +Employee(int salary)
 +getSalary(): int
}


class Employee {
 +Employee(int salary)
 +getSalary(): int
}

class Boss {
 +Boss(int salary)
 +getSalary(): int
}

Person <|-- Employee
Person <|-- SelfEmployed
Employee <|-- Boss
@enduml
